# Sport Logiq CSV EDA on Advanced Metric Queries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [19]:

# define teams in each conference
AHA = [
    'Air Force Academy Falcons', 
    'Army Black Knights',
    'Bentley University Falcons',
    'Canisius College Golden Griffins',
    'College of the Holy Cross Crusaders',
    'Mercyhurst University Lakers',
    'Niagara University Purple Eagles',
    'Robert Morris University Colonials',
    'Rochester Institute of Technology Tigers',
    'Sacred Heart University Pioneers'
]

CCHA = [
    'Augustana University Vikings',
    'Bemidji State University Beavers',
    'Bowling Green State University Falcons',
    'Ferris State University Bulldogs',
    'Lake Superior State University Lakers',
    'Michigan Tech University Huskies',
    'Minnesota State University Mavericks',
    'Northern Michigan University Wildcats',
    'The University of St. Thomas Tommies'
]

ECAC = [
    'Brown University Bears',
    'Clarkson University Golden Knights',
    'Colgate University Raiders',
    'Cornell University Big Red',
    'Dartmouth College Big Green',
    'Harvard University Crimson',
    'Princeton University Tigers',
    'Quinnipiac University Bobcats',
    'Rensselaer Polytechnic Institute Engineers',
    'St. Lawrence University Saints',
    'Union College Garnet Chargers',
    'Yale University Bulldogs'
]

HE = [
    'Boston College Eagles',
    'Boston University Terriers',
    'Merrimack College Warriors',
    'Northeastern University Huskies',
    'UMass Lowell River Hawks',
    'UMass Minutemen',
    'University of Connecticut Huskies',
    'University of Maine Black Bears',
    'University of New Hampshire Wildcats',
    'University of Vermont Catamounts',
    'Providence College Friars'
]

NCHC = [
    'Arizona State University Sun Devils',
    'Colorado College Tigers',
    'University of Denver Pioneers',
    'Miami University (Ohio) RedHawks',
    'University of Minnesota-Duluth Bulldogs',
    'University of North Dakota Fighting Hawks',
    'University of Nebraska Omaha Mavericks',
    'St. Cloud State University Huskies',
    'Western Michigan University Broncos'
]

BT = [
    'Michigan State University Spartans',
    'Michigan Wolverines',
    'Ohio State University Buckeyes',
    'Penn State University Nittany Lions'
    'University Of Notre Dame Fighting Irish',
    'University of Minnesota Golden Gophers',
    'University of Wisconsin Badgers'
]

INDE = [
    'University of Alaska Anchorage Seawolves',
    'University of Alaska Fairbanks Nanooks',
    'Lindenwood University Lions',
    'Long Island University Sharks',
    'Stonehill College Skyhawks'
]

In [20]:

import glob
file_paths = glob.glob('/Users/longer/uconn/team_data/*.csv')
dataframes = [pd.read_csv(file, index_col='Team') for file in file_paths]

master_df = pd.concat(dataframes, axis=1)
master_df = master_df.loc[:, ~master_df.columns.duplicated()]
master_df = master_df.reset_index()
master_df.to_csv("Master_Team_Baselines.csv", index=False)

ValueError: Index Team invalid

In [21]:
print(master_df.columns)

Index(['Team', 'Successful OZ Open Ice Dekes', 'Failed OZ Open Ice Dekes',
       'OZ Open Ice Deke Success Rate', 'Successful DZ Open Ice Dekes',
       'Failed DZ Open Ice Dekes', 'DZ Open Ice Deke Success Rate',
       'Successful NZ Open Ice Dekes', 'Failed NZ Open Ice Dekes',
       'NZ Open Ice Deke Success Rate',
       ...
       'Total DZ Penalties', 'Total NZ Undisciplined Penalties',
       'Total NZ Obstruction Penalties', 'Total NZ Penalties',
       'Total Undisciplined Penalties', 'Total Obstruction Penalties',
       'Total Penalties', 'Unnamed: 0', 'Conference', 'conference'],
      dtype='object', length=390)

In [22]:
conference_mapping = {}
lists = [AHA, CCHA, ECAC, HE, NCHC, BT, INDE]
names = ['Atlantic Hockey', 'CCHA', 'ECAC', 'Hockey East', 'NCHC', 'Big Ten', 'Independent']
for conf_list, conf_name in zip(lists, names):
    for team in conf_list:
        conference_mapping[team] = conf_name

In [23]:
master_df['conference'] = master_df['Team'].map(conference_mapping)
teams = master_df['Team']
conferences = master_df['conference']
numeric_metrics = master_df.drop(columns=['Team', 'conference', 'Conference'])

In [24]:

master_df.head()

,Team,Successful OZ Open Ice Dekes,Failed OZ Open Ice Dekes,OZ Open Ice Deke Success Rate,Successful DZ Open Ice Dekes,Failed DZ Open Ice Dekes,DZ Open Ice Deke Success Rate,Successful NZ Open Ice Dekes,Failed NZ Open Ice Dekes,NZ Open Ice Deke Success Rate,...,Total DZ Penalties,Total NZ Undisciplined Penalties,Total NZ Obstruction Penalties,Total NZ Penalties,Total Undisciplined Penalties,Total Obstruction Penalties,Total Penalties,Unnamed: 0,Conference,conference
0,Air Force Academy Falcons,203,664,0.234141,99,277,0.263298,56,210,0.210526,...,65,14,7,21,67,71,138,0,Atlantic Hockey,Atlantic Hockey
1,Arizona State University Sun Devils,138,531,0.206278,93,275,0.252717,53,203,0.207031,...,58,15,10,25,58,77,135,1,NCHC,NCHC
2,Army Black Knights,144,551,0.207194,66,264,0.200000,62,220,0.219858,...,71,8,9,17,62,81,143,2,Atlantic Hockey,Atlantic Hockey
3,Augustana University Vikings,188,653,0.223543,114,390,0.226190,81,257,0.239645,...,58,9,8,17,49,64,113,3,CCHA,CCHA
4,Bemidji State University Beavers,182,573,0.241060,76,228,0.250000,63,194,0.245136,...,57,13,10,23,54,70,124,4,CCHA,CCHA

In [25]:
scaler = StandardScaler()
scaled_df = scaler.fit_transform(numeric_metrics)

df_scaled = pd.DataFrame(scaled_df, columns=numeric_metrics.columns)
df_scaled.insert(0, 'Team', teams)
df_scaled.insert(1, 'Conference', conferences)
print(f'Dataset Shape: {df_scaled.shape}')
df_scaled.head()

Dataset Shape: (63, 389)

,Team,Conference,Successful OZ Open Ice Dekes,Failed OZ Open Ice Dekes,OZ Open Ice Deke Success Rate,Successful DZ Open Ice Dekes,Failed DZ Open Ice Dekes,DZ Open Ice Deke Success Rate,Successful NZ Open Ice Dekes,Failed NZ Open Ice Dekes,...,Total DZ Undisciplined Penalties,Total DZ Obstruction Penalties,Total DZ Penalties,Total NZ Undisciplined Penalties,Total NZ Obstruction Penalties,Total NZ Penalties,Total Undisciplined Penalties,Total Obstruction Penalties,Total Penalties,Unnamed: 0
0,Air Force Academy Falcons,Atlantic Hockey,-0.162420,0.359118,-0.480970,0.134802,-0.254371,0.454495,-1.069156,-0.681307,...,-0.057556,1.124145,0.622713,0.257343,-1.192069,-0.627193,-0.007824,0.544667,0.281587,-1.704773
1,Arizona State University Sun Devils,NCHC,-1.680934,-1.290582,-1.510774,-0.145171,-0.309252,0.107220,-1.267653,-0.918260,...,-0.807775,0.953492,-0.088729,0.527552,-0.381633,0.097819,-0.641554,1.172363,0.115793,-1.649780
2,Army Black Knights,Atlantic Hockey,-1.540764,-1.042507,-1.476911,-1.405048,-0.611099,-1.623082,-0.672161,-0.342803,...,0.067480,1.977412,1.232521,-1.363915,-0.651778,-1.352206,-0.359896,1.590827,0.557910,-1.594787
3,Augustana University Vikings,CCHA,-0.512846,0.222677,-0.872647,0.834733,2.846425,-0.763452,0.584990,0.909663,...,-0.807775,0.953492,-0.088729,-1.093706,-0.921924,-1.352206,-1.275285,-0.187644,-1.100030,-1.539795
4,Bemidji State University Beavers,CCHA,-0.653017,-0.769624,-0.225249,-0.938427,-1.598963,0.018029,-0.605995,-1.222913,...,-1.307921,1.465452,-0.190363,-0.012867,-0.381633,-0.264687,-0.923212,0.440051,-0.492119,-1.484802

**Now with our teams properly seperated by conference, we are able to compare and contrast conferences and perform EDA**

# EDA on Conferece Play

In [26]:
conference_baselines = df_scaled.groupby('Conference').mean(numeric_only=True)

conference_baselines.head()

,Successful OZ Open Ice Dekes,Failed OZ Open Ice Dekes,OZ Open Ice Deke Success Rate,Successful DZ Open Ice Dekes,Failed DZ Open Ice Dekes,DZ Open Ice Deke Success Rate,Successful NZ Open Ice Dekes,Failed NZ Open Ice Dekes,NZ Open Ice Deke Success Rate,Successful Open Ice Dekes,...,Total DZ Undisciplined Penalties,Total DZ Obstruction Penalties,Total DZ Penalties,Total NZ Undisciplined Penalties,Total NZ Obstruction Penalties,Total NZ Penalties,Total Undisciplined Penalties,Total Obstruction Penalties,Total Penalties,Unnamed: 0
Conference,,,,,,,,,,,,,,,,,,,,,
Atlantic Hockey,0.012793,0.044063,-0.048808,0.382111,0.522200,0.120763,0.373259,0.307125,0.179055,0.216652,...,0.292546,0.714577,0.663367,-0.093930,0.347758,0.170320,0.224544,0.837592,0.618701,-0.615918
Big Ten,1.005668,0.656809,0.767877,0.302785,-0.150096,0.530402,0.664389,0.530538,0.451398,0.897750,...,0.017465,-0.582389,-0.332652,0.527552,-0.327604,0.134070,0.245668,-0.187644,0.093687,0.472937
CCHA,-0.193569,-0.239019,-0.013960,0.160725,0.401156,-0.044203,-0.253110,-0.278863,-0.122224,-0.130594,...,-0.043664,0.498416,0.261346,0.167273,0.338753,0.339490,-0.039119,-0.048157,-0.056142,-0.604919
ECAC,-0.454442,-0.198017,-0.467512,-0.347373,0.004029,-0.507456,-0.269652,-0.007119,-0.337996,-0.466706,...,-0.120075,-0.027765,-0.114137,-0.598321,-0.314097,-0.612089,-0.500725,-0.309696,-0.556594,-0.151230
Hockey East,0.202873,-0.020888,0.302585,0.020267,-0.249381,0.224372,0.013558,-0.278179,0.215398,0.140487,...,-0.353097,-0.241082,-0.430590,-0.283077,-0.455309,-0.495373,-0.244673,-0.216176,-0.306229,0.354953

In [27]:
display(df_scaled.columns)
display(df_scaled.shape)

Index(['Team', 'Conference', 'Successful OZ Open Ice Dekes',
       'Failed OZ Open Ice Dekes', 'OZ Open Ice Deke Success Rate',
       'Successful DZ Open Ice Dekes', 'Failed DZ Open Ice Dekes',
       'DZ Open Ice Deke Success Rate', 'Successful NZ Open Ice Dekes',
       'Failed NZ Open Ice Dekes',
       ...
       'Total DZ Undisciplined Penalties', 'Total DZ Obstruction Penalties',
       'Total DZ Penalties', 'Total NZ Undisciplined Penalties',
       'Total NZ Obstruction Penalties', 'Total NZ Penalties',
       'Total Undisciplined Penalties', 'Total Obstruction Penalties',
       'Total Penalties', 'Unnamed: 0'],
      dtype='object', length=389)

(63, 389)

**Have to statistically prove that the difference in conference play is significant**

In [28]:
missing_filter = df_scaled['Conference'].isna()
problem_teams = df_scaled[missing_filter]
print(problem_teams[['Team', 'Conference']])

                                       Team Conference
33      Penn State University Nittany Lions        NaN
48  University Of Notre Dame Fighting Irish        NaN

In [29]:
df_scaled.loc[[33, 48], 'Conference'] = 'Big Ten'

In [30]:
from tqdm import tqdm
import scipy.stats as stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey_loop = df_scaled.copy()

metrics_to_test = [col for col in tukey_loop.columns if col not in ['Team', 'Conference']]

all_anova_results = {}
significant_tukey_reports = {}

for metric in tqdm(metrics_to_test, desc="Analyzing Hockey Metrics"):
    groups = [group[metric].values for name, group in df_scaled.groupby('Conference')]
    f_stat, anova_p_value = stats.f_oneway(*groups)
    
    all_anova_results[metric] = {
        'F-Stat': f_stat, 
        'P-Value': anova_p_value,
        'Significant': anova_p_value <= 0.05
    }
    
    if anova_p_value <= 0.05:
        print(f"Kept: {metric} (p={anova_p_value:.4f})")
        
        tukey_results = pairwise_tukeyhsd(endog=df_scaled[metric],
                                          groups=df_scaled['Conference'],
                                          alpha=0.05)
        
        significant_tukey_reports[metric] = tukey_results
    
    else: 
        tukey_loop.drop(columns=[metric], inplace=True)
        print(f'Popped: {metric} (p={anova_p_value:.4f})')

print("\n--- Loop Complete ---")
print(f"Remaining columns in tukey_loop: {tukey_loop.columns.tolist()}")

Analyzing Hockey Metrics:   0%|          | 0/387 [00:00<?, ?it/s]

Kept: Successful OZ Open Ice Dekes (p=0.0221)

Analyzing Hockey Metrics:   0%|          | 1/387 [00:00<01:31,  4.22it/s]

Kept: Failed OZ Open Ice Dekes (p=0.0077)

Analyzing Hockey Metrics:   1%|          | 2/387 [00:00<01:32,  4.14it/s]

Popped: OZ Open Ice Deke Success Rate (p=0.3350)
Popped: Successful DZ Open Ice Dekes (p=0.2641)
Popped: Failed DZ Open Ice Dekes (p=0.1065)
Popped: DZ Open Ice Deke Success Rate (p=0.3365)
Popped: Successful NZ Open Ice Dekes (p=0.3752)
Popped: Failed NZ Open Ice Dekes (p=0.0589)
Popped: NZ Open Ice Deke Success Rate (p=0.7823)
Kept: Successful Open Ice Dekes (p=0.0277)

Analyzing Hockey Metrics:   3%|▎         | 12/387 [00:00<00:25, 14.46it/s]

Kept: Failed Open Ice Dekes (p=0.0016)
Popped: Open Ice Deke Success Rate (p=0.2896)
Kept: Dump In Rate (p=0.0008)
Kept: Total Dump In Attempts (p=0.0071)

Analyzing Hockey Metrics:   4%|▍         | 16/387 [00:01<00:40,  9.22it/s]

Kept: Dump Ins Below Hash Marks (p=0.0123)
Popped: Dump Ins Below Hash Marks Rate (p=0.4530)
Kept: Total Chip In Attempts (p=0.0319)
Kept: Chip Ins Below Hash Marks (p=0.0423)

Analyzing Hockey Metrics:   5%|▍         | 18/387 [00:02<00:51,  7.21it/s]

Popped: Chip Ins Below Hash Marks Rate (p=0.9473)
Popped: Offensive Dump-Ins with Recovery After (p=0.1525)
Popped: Offensive Dump-In Recovery Rate (p=0.7507)
Popped: Total Offensive Dump-In Recoveries (p=0.1525)
Popped: Offensive Dump-In Recoveries with Shot On Net After (p=0.4086)
Popped: Offensive Dump-In Recoveries with Shot On Net After Rate (p=0.3779)
Popped: Offensive Dump-In Recoveries with Scoring Chance After (p=0.6514)
Popped: Offensive Dump-In Recoveries with Scoring Chance After Rate (p=0.7770)
Kept: Total Self Chip-In Recoveries (p=0.0017)

Analyzing Hockey Metrics:   7%|▋         | 27/387 [00:02<00:24, 14.97it/s]

Popped: Self Chip-In Recoveries with Shot On Net After (p=0.0807)
Popped: Self Chip-In Recoveries with Shot On Net After Rate (p=0.6715)
Popped: Self Chip-In Recoveries with Scoring Chance After (p=0.1675)
Popped: Self Chip-In Recoveries with Scoring Chance After Rate (p=0.1365)
Popped: Total Goals (p=0.0521)
Popped: True Shooting Percentage (p=0.1205)
Kept: Expected Goals (p=0.0275)

Analyzing Hockey Metrics:  10%|▉         | 37/387 [00:02<00:19, 17.69it/s]

Popped: Actual to Expected Goals (p=0.7465)
Kept: Grade A Shot Opportunities (p=0.0082)
Popped: Grade B Shot Opportunities (p=0.1435)
Kept: Grade C Shot Opportunities (p=0.0042)
Kept: Total OZ Entry Pass attempts in the NZ (p=0.0010)

Analyzing Hockey Metrics:  11%|█         | 41/387 [00:03<00:31, 11.14it/s]

Kept: Successful OZ Entry Pass Attempts (p=0.0004)
Popped: OZ Entry Passing Success Rate (p=0.1389)
Popped: OZ Entry Passing Tendency (p=0.2100)
Kept: Total North Pass Attempts in the NZ (p=0.0006)

Analyzing Hockey Metrics:  12%|█▏        | 45/387 [00:03<00:33, 10.11it/s]

Kept: Successful North NZ Pass Attempts (p=0.0003)
Popped: NZ North Passing Success Rate (p=0.2029)
Popped: NZ North Passing Tendency (p=0.4100)
Kept: Total South Pass Attempts in the NZ (p=0.0203)

Analyzing Hockey Metrics:  12%|█▏        | 47/387 [00:04<00:34,  9.85it/s]

Kept: Successful South NZ Pass Attempts (p=0.0448)
Popped: NZ South Passing Success Rate (p=0.2401)

Analyzing Hockey Metrics:  13%|█▎        | 51/387 [00:04<00:35,  9.40it/s]

Popped: NZ South Passing Tendency (p=0.2694)
Kept: Total East-West Pass Attempts in the NZ (p=0.0039)
Kept: Successful East-West NZ Pass Attempts (p=0.0006)

Analyzing Hockey Metrics:  14%|█▎        | 53/387 [00:04<00:46,  7.22it/s]

Kept: NZ East-West Passing Success Rate (p=0.0207)
Popped: NZ East-West Passing Tendency (p=0.3829)
Kept: NZ Pass Attempts (p=0.0003)

Analyzing Hockey Metrics:  14%|█▍        | 56/387 [00:05<00:50,  6.62it/s]

Kept: Successful NZ Passes (p=0.0002)
Popped: NZ Passing Success Rate (p=0.5735)
Kept: Total OZ Pass Receptions (p=0.0129)

Analyzing Hockey Metrics:  15%|█▌        | 59/387 [00:05<00:50,  6.54it/s]

Kept: Total OZ Pass Receptions in the Slot (p=0.0343)
Kept: Total OZ Pass Receptions Outside the Slot (p=0.0127)

Analyzing Hockey Metrics:  16%|█▌        | 61/387 [00:06<00:57,  5.62it/s]

Kept: Total DZ Pass Receptions (p=0.0145)
Kept: Total NZ Pass Receptions (p=0.0002)

Analyzing Hockey Metrics:  16%|█▋        | 63/387 [00:06<01:03,  5.07it/s]

Kept: Total Carry-Out Attempts (p=0.0387)
Kept: Carry-Outs with Play After (p=0.0363)

Analyzing Hockey Metrics:  17%|█▋        | 65/387 [00:07<01:06,  4.86it/s]

Kept: Carry-Out with Play After Rate (p=0.0221)
Kept: Successful Pass-Out Attempts (p=0.0011)

Analyzing Hockey Metrics:  17%|█▋        | 67/387 [00:07<01:08,  4.66it/s]

Kept: Failed Pass-Out Attempts (p=0.0092)
Kept: Pass-Out Success Rate (p=0.0187)

Analyzing Hockey Metrics:  18%|█▊        | 69/387 [00:08<01:15,  4.23it/s]

Kept: Pass-Outs with Play After (p=0.0022)
Kept: Pass-Out with Play After Rate (p=0.0380)

Analyzing Hockey Metrics:  18%|█▊        | 71/387 [00:08<01:13,  4.29it/s]

Kept: Controlled Exits (p=0.0002)
Kept: Controlled Exits with Play After (p=0.0002)

Analyzing Hockey Metrics:  19%|█▉        | 73/387 [00:09<01:13,  4.27it/s]

Kept: Controlled Exit with Play After Rate (p=0.0011)
Kept: Successful Defensive Dump-In Recoveries (p=0.0060)

Analyzing Hockey Metrics:  19%|█▉        | 75/387 [00:09<01:17,  4.00it/s]

Kept: Failed Defensive Dump-In Recoveries (p=0.0003)
Popped: Defensive Dump-In Recovery Exit Rate (p=0.2237)
Kept: Total Dump Out Attempts (p=0.0105)

Analyzing Hockey Metrics:  20%|██        | 78/387 [00:10<01:00,  5.07it/s]

Kept: Dump Out Rate (p=0.0130)
Kept: Successful Dump Out Attempts (p=0.0029)

Analyzing Hockey Metrics:  21%|██        | 81/387 [00:10<00:50,  6.12it/s]

Popped: Dump Out Success Rate (p=0.4918)
Kept: Total Icings (p=0.0381)
Kept: Opp Flip Dump-Out Recovs (p=0.0253)

Analyzing Hockey Metrics:  22%|██▏       | 85/387 [00:10<00:38,  7.92it/s]

Popped: Opp Flip Dump-Out Recovs With CE Percentage (p=0.0644)
Popped: Opp Flip Dump-Out Recovs With CE With OZ Possession Percentage (p=0.2480)
Kept: Opp Flip Dump-Out Recovs With Dump-In Percentage (p=0.0400)
Popped: Opp Flip Dump-Out Recovs With Dump-In and Recovery Percentage (p=0.3370)
Kept: Quick-Up Opp Flip Dump-Out Recovs (p=0.0354)

Analyzing Hockey Metrics:  22%|██▏       | 87/387 [00:11<00:36,  8.21it/s]

Popped: Quick-Up Opp Flip Dump-Out Recovs With CE Percentage (p=0.1139)
Popped: Quick-Up Opp Flip Dump-Out Recovs With Mid Ice CE (p=0.1442)
Popped: Quick-Up Opp Flip Dump-Out Recovs With CE With OZ Possession Percentage (p=0.1947)
Popped: Quick-Up Opp Flip Dump-Out Recovs With Dump-In Percentage (p=0.4267)
Popped: Quick-Up Opp Flip Dump-Out Recovs With Dump-In and Recovery Percentage (p=0.9169)
Popped: Total Opp Dump-Out Recovs (p=0.1040)
Kept: Opp Dump-Out Recovs With CE Percentage (p=0.0012)

Analyzing Hockey Metrics:  24%|██▍       | 94/387 [00:11<00:19, 14.89it/s]

Popped: Opp Dump-Out Recovs With CE With OZ Possession Percentage (p=0.6559)
Kept: Opp Dump-Out Recovs With Dump-In Percentage (p=0.0301)

Analyzing Hockey Metrics:  25%|██▍       | 96/387 [00:11<00:22, 13.06it/s]

Popped: Opp Dump-Out Recovs With Dump-In and Recovery Percentage (p=0.5142)
Kept: Quick-Up Opp Dump-Out Recovs (p=0.0156)

Analyzing Hockey Metrics:  26%|██▌       | 100/387 [00:12<00:26, 10.88it/s]

Popped: Quick-Up Opp Dump-Out Recovs With CE Percentage (p=0.1043)
Kept: Quick-Up Opp Dump-Out Recovs With Mid Ice CE (p=0.0265)
Popped: Quick-Up Opp Dump-Out Recovs With CE With OZ Possession Percentage (p=0.9547)
Popped: Quick-Up Opp Dump-Out Recovs With Dump-In Percentage (p=0.1399)
Popped: Quick-Up Opp Dump-Out Recovs With Dump-In and Recovery Percentage (p=0.9876)
Popped: Rim Dump-Ins (p=0.1569)
Popped: Rim Dump-Ins Recovery Rate (p=0.4066)
Popped: Rim Dump-Ins Recoveries (p=0.5617)
Popped: Rim Dump-Ins Recoveries with Shot On Net After Rate (p=0.6761)
Popped: Rim Dump-Ins Recoveries with Scoring Chance After Rate (p=0.9300)
Kept: Cross-Ice Dump-Ins (p=0.0077)

Analyzing Hockey Metrics:  29%|██▉       | 114/387 [00:12<00:13, 20.21it/s]

Popped: Cross-Ice Dump-Ins Recovery Rate (p=0.2238)
Popped: Cross-Ice Dump-Ins Recoveries (p=0.0759)
Popped: Cross-Ice Dump-Ins Recoveries with Shot On Net After Rate (p=0.6939)
Popped: Cross-Ice Dump-Ins Recoveries with Scoring Chance After Rate (p=0.6244)
Kept: Same-Side Dump-Ins (p=0.0219)
Popped: Same-Side Dump-Ins Recovery Rate (p=0.8389)
Popped: Same-Side Dump-Ins Recoveries (p=0.0584)
Popped: Same-Side Dump-Ins Recoveries with Shot On Net After Rate (p=0.3994)
Popped: Same-Side Dump-Ins Recoveries with Scoring Chance After Rate (p=0.3627)
Kept: Soft Dump-Ins (p=0.0449)

Analyzing Hockey Metrics:  31%|███       | 119/387 [00:12<00:12, 21.05it/s]

Popped: Soft Dump-Ins Recovery Rate (p=0.6569)
Popped: Soft Dump-Ins Recoveries (p=0.2780)
Popped: Soft Dump-Ins Recoveries with Shot On Net After Rate (p=0.9069)
Popped: Soft Dump-Ins Recoveries with Scoring Chance After Rate (p=0.9127)
Kept: Total Shot From Slot Attempts (p=0.0056)

Analyzing Hockey Metrics:  32%|███▏      | 124/387 [00:12<00:12, 21.23it/s]

Kept: Total Successful Shot From Slot Attempts (p=0.0072)
Kept: Goals From Slot (p=0.0282)
Kept: Scoring Chances Off-the-Rush (p=0.0050)

Analyzing Hockey Metrics:  33%|███▎      | 129/387 [00:13<00:22, 11.22it/s]

Kept: Scoring Chances Off-the-Rush On Net (p=0.0045)
Popped: Goals Off-the-Rush From Slot (p=0.0981)
Kept: Scoring Chances Off-the-Cycle (p=0.0026)
Kept: Scoring Chances Off-the-Cycle On Net (p=0.0016)

Analyzing Hockey Metrics:  34%|███▍      | 131/387 [00:14<00:29,  8.80it/s]

Kept: Goals Off-the-Cycle From Slot (p=0.0126)
Kept: Scoring Chances Off-the-Forecheck (p=0.0008)

Analyzing Hockey Metrics:  35%|███▍      | 134/387 [00:14<00:37,  6.75it/s]

Kept: Scoring Chances Off-the-Forecheck On Net (p=0.0121)
Popped: Goals Off-the-Forecheck From Slot (p=0.3726)
Kept: Scoring Chances Off OZ Play (p=0.0025)

Analyzing Hockey Metrics:  35%|███▌      | 137/387 [00:15<00:37,  6.61it/s]

Kept: Scoring Chances Off OZ Play On Net (p=0.0018)
Kept: Goals Off OZ Play From Slot (p=0.0301)

Analyzing Hockey Metrics:  36%|███▌      | 138/387 [00:15<00:40,  6.14it/s]

Popped: 2nd Chance Scoring Chances (p=0.0550)
Popped: 2nd Chance Scoring Chances On Net (p=0.2541)
Popped: 2nd Chance Scoring Chances Goals From Slot (p=0.9864)
Kept: Offense Generating Plays (p=0.0233)

Analyzing Hockey Metrics:  37%|███▋      | 143/387 [00:16<00:31,  7.83it/s]

Kept: Possession Driving (p=0.0001)
Kept: Slot Driving Plays (p=0.0179)

Analyzing Hockey Metrics:  37%|███▋      | 145/387 [00:16<00:38,  6.23it/s]

Kept: Total Carry to Slot (p=0.0114)
Popped: Percentage of Play in OZ (p=0.6946)
Popped: Percentage of Play in DZ (p=0.5332)
Popped: Percentage of Play in NZ (p=0.3612)
Kept: Successful OZ Stick Checks (p=0.0005)

Analyzing Hockey Metrics:  39%|███▉      | 151/387 [00:16<00:25,  9.21it/s]

Popped: Successful DZ Stick Checks (p=0.1155)
Kept: Successful NZ Stick Checks (p=0.0201)
Kept: Successful Stick Checks (p=0.0017)

Analyzing Hockey Metrics:  40%|███▉      | 153/387 [00:17<00:34,  6.69it/s]

Kept: Total Carry Ins (p=0.0001)
Kept: Carry Controlled Entries with Play After (p=0.0004)

Analyzing Hockey Metrics:  40%|███▉      | 154/387 [00:17<00:39,  5.95it/s]

Popped: Carry Controlled Entry with Play After Rate (p=0.4017)
Kept: Carry Controlled Entries with Shot On Net After (p=0.0005)

Analyzing Hockey Metrics:  40%|████      | 156/387 [00:17<00:34,  6.75it/s]

Popped: Carry Controlled Entry with Shot On Net After Rate (p=0.7827)
Kept: Carry Controlled Entries with Scoring Chance After (p=0.0004)

Analyzing Hockey Metrics:  41%|████▏     | 160/387 [00:18<00:29,  7.66it/s]

Popped: Carry Controlled Entry with Scoring Chance After Rate (p=0.1409)
Kept: Successful Pass Controlled Entries (p=0.0004)
Popped: Failed Pass Controlled Entries (p=0.3353)
Kept: Pass Controlled Entry Success Rate (p=0.0274)

Analyzing Hockey Metrics:  42%|████▏     | 163/387 [00:18<00:32,  6.99it/s]

Kept: Pass Controlled Entries with Play After (p=0.0026)
Popped: Pass Controlled Entry with Play After Rate (p=0.1987)
Popped: Pass Controlled Entries with Shot On Net After (p=0.1298)
Popped: Pass Controlled Entry with Shot On Net After Rate (p=0.1247)
Kept: Pass Controlled Entries with Scoring Chance After (p=0.0104)

Analyzing Hockey Metrics:  44%|████▎     | 169/387 [00:19<00:22,  9.59it/s]

Popped: Pass Controlled Entry with Scoring Chance After Rate (p=0.2983)
Kept: Controlled Entries (p=0.0000)
Kept: Controlled Entries with Play After (p=0.0002)

Analyzing Hockey Metrics:  44%|████▍     | 170/387 [00:19<00:27,  7.87it/s]

Popped: Controlled Entry with Play After Rate (p=0.4837)
Kept: Controlled Entries with Shot On Net After (p=0.0009)

Analyzing Hockey Metrics:  44%|████▍     | 172/387 [00:19<00:28,  7.63it/s]

Popped: Controlled Entry with Shot On Net After Rate (p=0.6821)
Kept: Controlled Entries with Scoring Chance After (p=0.0004)

Analyzing Hockey Metrics:  45%|████▌     | 176/387 [00:20<00:26,  8.02it/s]

Popped: Controlled Entry with Scoring Chance After Rate (p=0.1370)
Kept: Odd Man Rushes Against (+Against) (p=0.0001)
Kept: Total Offsides (p=0.0140)

Analyzing Hockey Metrics:  46%|████▌     | 178/387 [00:20<00:34,  6.12it/s]

Kept: Successful OZ Defensive Touches (p=0.0003)
Popped: Successful DZ Defensive Touches (p=0.1332)
Kept: Successful NZ Defensive Touches (p=0.0067)

Analyzing Hockey Metrics:  47%|████▋     | 181/387 [00:21<00:34,  6.03it/s]

Kept: Successful Defensive Touches (p=0.0001)
Popped: Total Controlled Entries Against (p=0.0892)
Popped: Denied Controlled Entries Against (p=0.0514)
Popped: DZ Entry Denial Rate (p=0.7765)
Popped: Total Entry Attempts Against (p=0.0689)
Popped: Average Controlled Entry Against Gap Distance (p=0.8938)
Popped: NZ Denials (p=0.1993)
Popped: Overall DZ Denial Rate (p=0.7950)
Popped: Overall DZ Denial and Exit Percentage (p=0.7074)
Popped: Entries Against Without Cycle Pass Percentage (p=0.3947)
Popped: Entries Against Without Shot On Net Percentage (p=0.5945)
Popped: Entries Against Without Slot Shot Attempt Percentage (p=0.5459)
Kept: Successful OZ Body Checks (p=0.0200)

Analyzing Hockey Metrics:  50%|█████     | 195/387 [00:21<00:12, 15.54it/s]

Kept: Successful DZ Body Checks (p=0.0033)
Popped: Successful NZ Body Checks (p=0.0652)
Kept: Successful Body Checks (p=0.0004)
Kept: Successful OZ Passes (p=0.0197)

Analyzing Hockey Metrics:  51%|█████     | 197/387 [00:22<00:17, 10.72it/s]

Kept: Failed OZ Passes (p=0.0146)

Analyzing Hockey Metrics:  51%|█████▏    | 199/387 [00:22<00:19,  9.45it/s]

Popped: OZ Passing Success Rate (p=0.9027)
Kept: Successful DZ Passes (p=0.0012)
Kept: Failed DZ Passes (p=0.0009)

Analyzing Hockey Metrics:  52%|█████▏    | 201/387 [00:22<00:24,  7.56it/s]

Popped: DZ Passing Success Rate (p=0.0658)
Kept: Failed NZ Passes (p=0.0090)

Analyzing Hockey Metrics:  53%|█████▎    | 204/387 [00:23<00:27,  6.74it/s]

Kept: Successful Passes (p=0.0005)
Kept: Failed Passes (p=0.0015)

Analyzing Hockey Metrics:  53%|█████▎    | 207/387 [00:23<00:25,  6.93it/s]

Popped: Passing Success Rate (p=0.6750)
Kept: Total Outlet Pass Attempts (p=0.0048)
Kept: Successful Outlet Pass Attempts (p=0.0058)

Analyzing Hockey Metrics:  54%|█████▎    | 208/387 [00:24<00:28,  6.20it/s]

Popped: Outlet Pass Success Rate (p=0.0583)
Popped: Outlet Passing Tendency (p=0.0626)
Popped: Total Stretch Pass Attempts (p=0.2745)
Popped: Successful Stretch Pass Attempts (p=0.1979)
Kept: Stretch Pass Success Rate (p=0.0284)

Analyzing Hockey Metrics:  56%|█████▌    | 215/387 [00:24<00:17, 10.11it/s]

Popped: Stretch Passing Tendency (p=0.9933)
Kept: Total D2D Pass Attempts in the DZ (p=0.0040)
Kept: Successful D2D Pass Attempts (p=0.0072)
Kept: D2D Passing Success Rate (p=0.0338)

Analyzing Hockey Metrics:  57%|█████▋    | 219/387 [00:25<00:20,  8.02it/s]

Popped: D2D Passing Tendency (p=0.0650)
Kept: DZ Pass Attempts (p=0.0005)
Popped: Successful OZ LPRs (p=0.1327)
Popped: Successful OZ LPRs After Shot (p=0.3750)
Popped: Shot Attempts Recovery Rate (p=0.7355)
Popped: Successful OZ Rebound LPRs (p=0.2091)
Popped: Successful OZ Contested LPRs (p=0.3989)
Popped: Failed OZ Contested LPRs (p=0.2272)
Popped: OZ Contested LPR Recovery Rate (p=0.5740)
Kept: Successful DZ LPRs (p=0.0000)

Analyzing Hockey Metrics:  59%|█████▉    | 229/387 [00:25<00:12, 13.15it/s]

Kept: Total Defensive Dump-In Recoveries (p=0.0017)
Popped: Successful DZ Rebound LPRs (p=0.0515)
Popped: Successful DZ Contested LPRs (p=0.2279)
Popped: Failed DZ Contested LPRs (p=0.1798)
Popped: DZ Contested LPR Recovery Rate (p=0.1426)
Kept: Successful NZ LPRs (p=0.0449)

Analyzing Hockey Metrics:  61%|██████    | 237/387 [00:26<00:09, 15.35it/s]

Popped: Successful NZ Contested LPRs (p=0.6441)
Popped: Failed NZ Contested LPRs (p=0.2538)
Popped: NZ Contested LPR Recovery Rate (p=0.4564)
Kept: Successful LPRs (p=0.0011)
Popped: Successful Contested LPRs (p=0.1375)
Kept: Failed Contested LPRs (p=0.0237)

Analyzing Hockey Metrics:  64%|██████▎   | 246/387 [00:26<00:07, 18.88it/s]

Popped: Overall Contested LPR Recovery Rate (p=0.1796)
Popped: Press Def Dumpin Recov from Rim Dumpins w Play Rate (p=0.8527)
Popped: Succ Press Def Dumpin Recovs from Rim Dumpins (p=0.1793)
Popped: Failed Press Def Dumpin Recovs from Rim Dumpins (p=0.5859)
Popped: Press Def Dumpin Recov from Rim Dumpins Exit Rate (p=0.3156)
Popped: No Press Def Dumpin Recov from Rim Dumpins w Play Rate (p=0.1192)
Kept: Succ No Press Def Dumpin Recovs from Rim Dumpins (p=0.0204)
Kept: Failed No Press Def Dumpin Recovs from Rim Dumpins (p=0.0077)

Analyzing Hockey Metrics:  64%|██████▍   | 248/387 [00:26<00:08, 15.92it/s]

Popped: No Press Def Dumpin Recov from Rim Dumpins Exit Rate (p=0.0617)
Popped: Press Def Dumpin Recov from Cross-Ice Dumpins w Play Rate (p=0.6627)
Popped: Succ Press Def Dumpin Recovs from Cross-Ice Dumpins (p=0.0612)
Popped: Failed Press Def Dumpin Recovs from Cross-Ice Dumpins (p=0.1802)
Popped: Press Def Dumpin Recov from Cross-Ice Dumpins Exit Rate (p=0.8548)
Popped: No Press Def Dumpin Recov from Cross-Ice Dumpins w Play Rate (p=0.1674)
Kept: Succ No Press Def Dumpin Recovs from Cross-Ice Dumpins (p=0.0007)

Analyzing Hockey Metrics:  66%|██████▌   | 256/387 [00:27<00:08, 16.15it/s]

Popped: Failed No Press Def Dumpin Recovs from Cross-Ice Dumpins (p=0.0654)
Kept: No Press Def Dumpin Recov from Cross-Ice Dumpins Exit Rate (p=0.0195)
Popped: Press Def Dumpin Recov from Same-Side Dumpins w Play Rate (p=0.5241)
Popped: Succ Press Def Dumpin Recovs from Same-Side Dumpins (p=0.0880)
Popped: Failed Press Def Dumpin Recovs from Same-Side Dumpins (p=0.1123)
Popped: Press Def Dumpin Recov from Same-Side Dumpins Exit Rate (p=0.4582)
Popped: No Press Def Dumpin Recov from Same-Side Dumpins w Play Rate (p=0.0589)
Kept: Succ No Press Def Dumpin Recovs from Same-Side Dumpins (p=0.0185)

Analyzing Hockey Metrics:  68%|██████▊   | 264/387 [00:27<00:07, 16.16it/s]

Kept: Failed No Press Def Dumpin Recovs from Same-Side Dumpins (p=0.0026)
Popped: No Press Def Dumpin Recov from Same-Side Dumpins Exit Rate (p=0.4341)
Kept: Press Def Dumpin Recov from Soft Dumpins w Play Rate (p=0.0173)

Analyzing Hockey Metrics:  69%|██████▊   | 266/387 [00:27<00:08, 13.99it/s]

Popped: Succ Press Def Dumpin Recovs from Soft Dumpins (p=0.1389)
Kept: Failed Press Def Dumpin Recovs from Soft Dumpins (p=0.0435)

Analyzing Hockey Metrics:  69%|██████▉   | 268/387 [00:28<00:09, 12.62it/s]

Popped: Press Def Dumpin Recov from Soft Dumpins Exit Rate (p=0.1603)
Popped: No Press Def Dumpin Recov from Soft Dumpins w Play Rate (p=0.0629)
Kept: Succ No Press Def Dumpin Recovs from Soft Dumpins (p=0.0242)

Analyzing Hockey Metrics:  71%|███████   | 274/387 [00:28<00:08, 12.73it/s]

Popped: Failed No Press Def Dumpin Recovs from Soft Dumpins (p=0.6366)
Popped: No Press Def Dumpin Recov from Soft Dumpins Exit Rate (p=0.2180)
Popped: Press Def Dumpin Recov with Play After Rate (p=0.4592)
Kept: Succ Press Def Dumpin Recovs (p=0.0418)
Kept: Failed Press Def Dumpin Recovs (p=0.0140)

Analyzing Hockey Metrics:  71%|███████▏  | 276/387 [00:28<00:09, 11.72it/s]

Popped: Press Def Dumpin Recov Exit Rate (p=0.5741)
Kept: No Press Def Dumpin Recov with Play After Rate (p=0.0142)

Analyzing Hockey Metrics:  72%|███████▏  | 278/387 [00:29<00:13,  8.32it/s]

Kept: Succ No Press Def Dumpin Recovs (p=0.0043)
Kept: Failed No Press Def Dumpin Recovs (p=0.0008)

Analyzing Hockey Metrics:  73%|███████▎  | 281/387 [00:29<00:13,  7.80it/s]

Popped: No Press Def Dumpin Recov Exit Rate (p=0.0624)
Kept: Successful OZ Offensive Touches (p=0.0197)
Kept: Failed OZ Offensive Touches (p=0.0136)

Analyzing Hockey Metrics:  73%|███████▎  | 284/387 [00:30<00:13,  7.45it/s]

Popped: OZ Offensive Touches Success Rate (p=0.5855)
Kept: Failed OZ Possessions (p=0.0015)
Popped: OZ True Turnover Rate (p=0.3625)
Popped: Failed DZ Possessions (+Against) (p=0.1159)
Popped: DZ True Turnover Rate (+Against) (p=0.6424)
Kept: Successful DZ Offensive Touches (p=0.0003)

Analyzing Hockey Metrics:  74%|███████▍  | 288/387 [00:30<00:09, 10.39it/s]

Kept: Failed DZ Offensive Touches (p=0.0002)
Kept: DZ Offensive Touches Success Rate (p=0.0488)

Analyzing Hockey Metrics:  75%|███████▌  | 291/387 [00:31<00:13,  6.87it/s]

Kept: Failed DZ Possessions (p=0.0472)
Popped: DZ True Turnover Rate (p=0.2351)
Popped: Failed OZ Possessions (+Against) (p=0.0527)
Popped: OZ True Turnover Rate (+Against) (p=0.1906)
Kept: Successful NZ Offensive Touches (p=0.0004)

Analyzing Hockey Metrics:  77%|███████▋  | 297/387 [00:31<00:09,  9.38it/s]

Kept: Failed NZ Offensive Touches (p=0.0034)
Popped: NZ Offensive Touches Success Rate (p=0.7814)
Kept: Failed NZ Possessions (p=0.0170)

Analyzing Hockey Metrics:  78%|███████▊  | 301/387 [00:32<00:08,  9.66it/s]

Popped: NZ True Turnover Rate (p=0.4544)
Popped: Failed NZ Possessions (+Against) (p=0.1008)
Kept: NZ True Turnover Rate (+Against) (p=0.0448)
Kept: Successful Offensive Touches (p=0.0004)

Analyzing Hockey Metrics:  78%|███████▊  | 303/387 [00:32<00:11,  7.07it/s]

Kept: Failed Offensive Touches (p=0.0005)
Popped: Offensive Touches Success Rate (p=0.6547)
Kept: Failed Possessions (p=0.0000)

Analyzing Hockey Metrics:  79%|███████▉  | 305/387 [00:32<00:10,  7.56it/s]

Popped: Overall True Turnover Rate (p=0.5191)
Kept: Failed Possessions (+Against) (p=0.0008)

Analyzing Hockey Metrics:  80%|███████▉  | 309/387 [00:33<00:09,  8.29it/s]

Popped: Overall True Turnover Rate (+Against) (p=0.1181)
Kept: OZ Time of Possession (p=0.0114)
Kept: DZ Time of Possession (p=0.0001)

Analyzing Hockey Metrics:  80%|████████  | 311/387 [00:33<00:12,  6.25it/s]

Kept: NZ Time of Possession (p=0.0010)
Kept: Total Time of Possession (p=0.0003)

Analyzing Hockey Metrics:  81%|████████  | 313/387 [00:34<00:14,  5.16it/s]

Kept: OZ Rating (p=0.0439)
Kept: DZ Rating (p=0.0000)

Analyzing Hockey Metrics:  81%|████████▏ | 315/387 [00:34<00:15,  4.76it/s]

Kept: NZ Rating (p=0.0010)
Kept: Overall Rating (p=0.0001)

Analyzing Hockey Metrics:  82%|████████▏ | 317/387 [00:34<00:15,  4.57it/s]

Kept: Total Events (p=0.0001)
Popped: OZ Events Ratio (p=0.4546)
Popped: DZ Events Ratio (p=0.4154)
Popped: NZ Events Ratio (p=0.6341)
Kept: Total Pass to Slot Attempts (p=0.0403)

Analyzing Hockey Metrics:  83%|████████▎ | 322/387 [00:35<00:08,  7.42it/s]

Kept: Successful Pass to Slot Attempts (p=0.0380)
Popped: Pass to Slot Success Rate (p=0.3182)
Popped: Pass to Slot Tendency (p=0.1710)
Popped: 1 Timers Pass from Slot (p=0.4396)
Popped: % of Pass Attempts to the Slot that are 1 Timers (p=0.6628)
Kept: Total Off-the-Rush Pass Attempts (p=0.0087)

Analyzing Hockey Metrics:  85%|████████▌ | 329/387 [00:35<00:05, 10.94it/s]

Kept: Successful Off-the-Rush Pass Attempts (p=0.0150)
Popped: Off-the-Rush Pass Success Rate (p=0.7516)
Popped: Off-the-Rush Passing Tendency (p=0.1596)
Popped: 1 Timers Pass from Off-the-Rush (p=0.9988)
Popped: % of Off-the-Rush Pass Attempts that are 1 Timers (p=0.8475)
Kept: Total North Pass Attempts in the OZ (p=0.0315)

Analyzing Hockey Metrics:  87%|████████▋ | 337/387 [00:36<00:03, 14.90it/s]

Popped: Successful North OZ Pass Attempts (p=0.0914)
Popped: OZ North Passing Success Rate (p=0.1550)
Popped: OZ North Passing Tendency (p=0.2034)
Kept: Total South Pass Attempts in the OZ (p=0.0283)
Kept: Successful South OZ Pass Attempts (p=0.0361)

Analyzing Hockey Metrics:  88%|████████▊ | 339/387 [00:36<00:03, 13.24it/s]

Popped: OZ South Passing Success Rate (p=0.2847)
Popped: OZ South Passing Tendency (p=0.6169)
Kept: Total East-West Pass Attempts in the OZ (p=0.0107)

Analyzing Hockey Metrics:  89%|████████▊ | 343/387 [00:36<00:04, 10.85it/s]

Kept: Successful East-West OZ Pass Attempts (p=0.0159)
Popped: OZ East-West Passing Success Rate (p=0.4620)
Kept: OZ East-West Passing Tendency (p=0.0095)
Kept: 1 Timers Pass from East-West (p=0.0319)

Analyzing Hockey Metrics:  89%|████████▉ | 345/387 [00:37<00:05,  8.15it/s]

Popped: % of East-West Pass Attempts that are 1 Timers (p=0.0598)
Kept: OZ Pass Attempts (p=0.0133)

Analyzing Hockey Metrics:  90%|████████▉ | 347/387 [00:37<00:04,  8.41it/s]

Popped: 1 Timers Pass from OZ (p=0.1702)
Popped: % of Total OZ Pass Attempts that are 1 Timers (p=0.1242)
Popped: Successful Blocked Shots (p=0.1136)
Popped: Failed Blocked Shots (p=0.9754)
Popped: Shot Block Success Rate (p=0.4324)
Kept: Base Successful OZ Blocked Passes (p=0.0000)

Analyzing Hockey Metrics:  91%|█████████ | 353/387 [00:37<00:02, 13.13it/s]

Popped: Base Failed OZ Blocked Passes (p=0.0591)
Popped: Base OZ Pass Block Success Rate (p=0.9482)
Popped: Successful OZ Blueline Holds (p=0.4660)
Popped: Failed OZ Blueline Holds (p=0.7820)
Popped: OZ Blueline Hold Success Rate (p=0.8449)
Kept: Successful OZ Blocked Passes (p=0.0016)

Analyzing Hockey Metrics:  94%|█████████▍| 365/387 [00:38<00:01, 19.16it/s]

Popped: Failed OZ Blocked Passes (p=0.0606)
Popped: OZ Pass Block Success Rate (p=0.9983)
Popped: Successful DZ Blocked Passes (p=0.0562)
Popped: Failed DZ Blocked Passes (p=0.7438)
Popped: DZ Pass Block Success Rate (p=0.7588)
Kept: Successful NZ Blocked Passes (p=0.0253)
Popped: Failed NZ Blocked Passes (p=0.0992)
Popped: NZ Pass Block Success Rate (p=0.4150)
Kept: Successful Blocked Passes (p=0.0000)

Analyzing Hockey Metrics:  95%|█████████▌| 368/387 [00:38<00:01, 17.17it/s]

Popped: Failed Blocked Passes (p=0.1127)
Popped: Pass Block Success Rate (p=0.7389)
Popped: OZ Reception Preventions (p=0.4435)
Kept: DZ Reception Preventions (p=0.0017)

Analyzing Hockey Metrics:  96%|█████████▌| 372/387 [00:38<00:00, 16.80it/s]

Popped: NZ Reception Preventions (p=0.2814)
Kept: Total Reception Preventions (p=0.0020)

Analyzing Hockey Metrics:  97%|█████████▋| 374/387 [00:39<00:00, 14.35it/s]

Popped: Total OZ Undisciplined Penalties (p=0.0684)
Kept: Total OZ Obstruction Penalties (p=0.0089)

Analyzing Hockey Metrics:  98%|█████████▊| 378/387 [00:39<00:00, 11.03it/s]

Kept: Total OZ Penalties (p=0.0289)
Popped: Total DZ Undisciplined Penalties (p=0.6856)
Kept: Total DZ Obstruction Penalties (p=0.0168)

Analyzing Hockey Metrics:  98%|█████████▊| 380/387 [00:39<00:00, 10.03it/s]

Popped: Total DZ Penalties (p=0.2440)
Kept: Total NZ Undisciplined Penalties (p=0.0127)

Analyzing Hockey Metrics:  99%|█████████▊| 382/387 [00:40<00:00,  9.54it/s]

Popped: Total NZ Obstruction Penalties (p=0.2888)
Popped: Total NZ Penalties (p=0.0533)
Popped: Total Undisciplined Penalties (p=0.0540)
Kept: Total Obstruction Penalties (p=0.0039)

Analyzing Hockey Metrics: 100%|██████████| 387/387 [00:40<00:00,  9.55it/s]

Popped: Total Penalties (p=0.0956)
Kept: Unnamed: 0 (p=0.0342)

--- Loop Complete ---
Remaining columns in tukey_loop: ['Team', 'Conference', 'Successful OZ Open Ice Dekes', 'Failed OZ Open Ice Dekes', 'Successful Open Ice Dekes', 'Failed Open Ice Dekes', 'Dump In Rate', 'Total Dump In Attempts', 'Dump Ins Below Hash Marks', 'Total Chip In Attempts', 'Chip Ins Below Hash Marks', 'Total Self Chip-In Recoveries', 'Expected Goals', 'Grade A Shot Opportunities', 'Grade C Shot Opportunities', 'Total OZ Entry Pass attempts in the NZ', 'Successful OZ Entry Pass Attempts', 'Total North Pass Attempts in the NZ', 'Successful North NZ Pass Attempts', 'Total South Pass Attempts in the NZ', 'Successful South NZ Pass Attempts', 'Total East-West Pass Attempts in the NZ', 'Successful East-West NZ Pass Attempts', 'NZ East-West Passing Success Rate', 'NZ Pass Attempts', 'Successful NZ Passes', 'Total OZ Pass Receptions', 'Total OZ Pass Receptions in the Slot', 'Total OZ Pass Receptions Outside the Slot', 'Total DZ Pass Receptions', 'Total NZ Pass Receptions', 'Total Carry-Out Attempts', 'Carry-Outs with Play After', 'Carry-Out with Play After Rate', 'Successful Pass-Out Attempts', 'Failed Pass-Out Attempts', 'Pass-Out Success Rate', 'Pass-Outs with Play After', 'Pass-Out with Play After Rate', 'Controlled Exits', 'Controlled Exits with Play After', 'Controlled Exit with Play After Rate', 'Successful Defensive Dump-In Recoveries', 'Failed Defensive Dump-In Recoveries', 'Total Dump Out Attempts', 'Dump Out Rate', 'Successful Dump Out Attempts', 'Total Icings', 'Opp Flip Dump-Out Recovs', 'Opp Flip Dump-Out Recovs With Dump-In Percentage', 'Quick-Up Opp Flip Dump-Out Recovs', 'Opp Dump-Out Recovs With CE Percentage', 'Opp Dump-Out Recovs With Dump-In Percentage', 'Quick-Up Opp Dump-Out Recovs', 'Quick-Up Opp Dump-Out Recovs With Mid Ice CE', 'Cross-Ice Dump-Ins', 'Same-Side Dump-Ins', 'Soft Dump-Ins', 'Total Shot From Slot Attempts', 'Total Successful Shot From Slot Attempts', 'Goals From Slot', 'Scoring Chances Off-the-Rush', 'Scoring Chances Off-the-Rush On Net', 'Scoring Chances Off-the-Cycle', 'Scoring Chances Off-the-Cycle On Net', 'Goals Off-the-Cycle From Slot', 'Scoring Chances Off-the-Forecheck', 'Scoring Chances Off-the-Forecheck On Net', 'Scoring Chances Off OZ Play', 'Scoring Chances Off OZ Play On Net', 'Goals Off OZ Play From Slot', 'Offense Generating Plays', 'Possession Driving', 'Slot Driving Plays', 'Total Carry to Slot', 'Successful OZ Stick Checks', 'Successful NZ Stick Checks', 'Successful Stick Checks', 'Total Carry Ins', 'Carry Controlled Entries with Play After', 'Carry Controlled Entries with Shot On Net After', 'Carry Controlled Entries with Scoring Chance After', 'Successful Pass Controlled Entries', 'Pass Controlled Entry Success Rate', 'Pass Controlled Entries with Play After', 'Pass Controlled Entries with Scoring Chance After', 'Controlled Entries', 'Controlled Entries with Play After', 'Controlled Entries with Shot On Net After', 'Controlled Entries with Scoring Chance After', 'Odd Man Rushes Against (+Against)', 'Total Offsides', 'Successful OZ Defensive Touches', 'Successful NZ Defensive Touches', 'Successful Defensive Touches', 'Successful OZ Body Checks', 'Successful DZ Body Checks', 'Successful Body Checks', 'Successful OZ Passes', 'Failed OZ Passes', 'Successful DZ Passes', 'Failed DZ Passes', 'Failed NZ Passes', 'Successful Passes', 'Failed Passes', 'Total Outlet Pass Attempts', 'Successful Outlet Pass Attempts', 'Stretch Pass Success Rate', 'Total D2D Pass Attempts in the DZ', 'Successful D2D Pass Attempts', 'D2D Passing Success Rate', 'DZ Pass Attempts', 'Successful DZ LPRs', 'Total Defensive Dump-In Recoveries', 'Successful NZ LPRs', 'Successful LPRs', 'Failed Contested LPRs', 'Succ No Press Def Dumpin Recovs from Rim Dumpins', 'Failed No Press Def Dumpin Recovs from Rim Dumpins', 'Succ No Press Def Dumpin Recovs from Cross-Ice Dumpins', 'No Press Def Dumpin Recov from Cross-Ice Dumpins Exit Rate', 'Succ No Press Def Dumpin Recovs from Same-Side Dumpins', 'Failed No Press Def Dumpin Recovs from Same-Side Dumpins', 'Press Def Dumpin Recov from Soft Dumpins w Play Rate', 'Failed Press Def Dumpin Recovs from Soft Dumpins', 'Succ No Press Def Dumpin Recovs from Soft Dumpins', 'Succ Press Def Dumpin Recovs', 'Failed Press Def Dumpin Recovs', 'No Press Def Dumpin Recov with Play After Rate', 'Succ No Press Def Dumpin Recovs', 'Failed No Press Def Dumpin Recovs', 'Successful OZ Offensive Touches', 'Failed OZ Offensive Touches', 'Failed OZ Possessions', 'Successful DZ Offensive Touches', 'Failed DZ Offensive Touches', 'DZ Offensive Touches Success Rate', 'Failed DZ Possessions', 'Successful NZ Offensive Touches', 'Failed NZ Offensive Touches', 'Failed NZ Possessions', 'NZ True Turnover Rate (+Against)', 'Successful Offensive Touches', 'Failed Offensive Touches', 'Failed Possessions', 'Failed Possessions (+Against)', 'OZ Time of Possession', 'DZ Time of Possession', 'NZ Time of Possession', 'Total Time of Possession', 'OZ Rating', 'DZ Rating', 'NZ Rating', 'Overall Rating', 'Total Events', 'Total Pass to Slot Attempts', 'Successful Pass to Slot Attempts', 'Total Off-the-Rush Pass Attempts', 'Successful Off-the-Rush Pass Attempts', 'Total North Pass Attempts in the OZ', 'Total South Pass Attempts in the OZ', 'Successful South OZ Pass Attempts', 'Total East-West Pass Attempts in the OZ', 'Successful East-West OZ Pass Attempts', 'OZ East-West Passing Tendency', '1 Timers Pass from East-West', 'OZ Pass Attempts', 'Base Successful OZ Blocked Passes', 'Successful OZ Blocked Passes', 'Successful NZ Blocked Passes', 'Successful Blocked Passes', 'DZ Reception Preventions', 'Total Reception Preventions', 'Total OZ Obstruction Penalties', 'Total OZ Penalties', 'Total DZ Obstruction Penalties', 'Total NZ Undisciplined Penalties', 'Total Obstruction Penalties', 'Unnamed: 0']

In [ ]:
tukey_loop.to_csv('ss_cols_df.csv')

cleaned_df = pd.read_csv('ss_cols_df.csv')

cleaned_conference_baselines = cleaned_df.groupby('Conference').mean(numeric_only=True)

In [32]:
cleaned_conference_baselines

,Unnamed: 0.1,Successful OZ Open Ice Dekes,Failed OZ Open Ice Dekes,Successful Open Ice Dekes,Failed Open Ice Dekes,Dump In Rate,Total Dump In Attempts,Dump Ins Below Hash Marks,Total Chip In Attempts,Chip Ins Below Hash Marks,...,Successful NZ Blocked Passes,Successful Blocked Passes,DZ Reception Preventions,Total Reception Preventions,Total OZ Obstruction Penalties,Total OZ Penalties,Total DZ Obstruction Penalties,Total NZ Undisciplined Penalties,Total Obstruction Penalties,Unnamed: 0
Conference,,,,,,,,,,,,,,,,,,,,,
Atlantic Hockey,19.800000,0.012793,0.044063,0.216652,0.286144,0.463172,0.561241,0.514828,0.475375,0.448341,...,-0.021864,0.042433,0.145471,-0.131051,0.449798,0.409561,0.714577,-0.093930,0.837592,-0.615918
Big Ten,39.857143,0.962282,0.733003,0.836184,0.619693,-1.301132,-0.487698,-0.471846,-0.752269,-0.755214,...,0.407089,0.576650,0.487216,0.635648,0.259444,0.721831,-0.314219,0.643356,-0.008303,0.487078
CCHA,20.000000,-0.193569,-0.239019,-0.130594,-0.116506,0.707995,0.732614,0.682087,0.609535,0.593783,...,0.478901,0.670884,0.962295,0.916047,-0.823454,-0.599782,0.498416,0.167273,-0.048157,-0.604919
ECAC,28.250000,-0.454442,-0.198017,-0.466706,-0.144880,0.001229,-0.489008,-0.505586,-0.399811,-0.408798,...,-0.662549,-0.759222,-0.679242,-0.553965,-0.290465,-0.611987,-0.027765,-0.598321,-0.309696,-0.151230
Hockey East,37.454545,0.202873,-0.020888,0.140487,-0.171655,-0.204844,-0.211968,-0.122970,-0.048272,-0.017731,...,-0.111981,-0.107158,-0.085905,-0.232441,0.183303,0.156920,-0.241082,-0.283077,-0.216176,0.354953
Independent,36.600000,-0.867945,-1.278178,-0.982803,-1.556967,0.498194,-0.717030,-0.737938,-0.460608,-0.398639,...,-0.632772,-1.373303,-0.826707,-0.857115,-0.669479,0.112982,-1.094349,1.176055,-1.191958,0.307959
NCHC,40.222222,0.271071,0.619598,0.236074,0.584541,-0.238689,0.332539,0.347250,0.295342,0.283651,...,0.600570,0.739676,-0.032943,0.234061,0.657071,0.144715,-0.108351,-0.072914,0.463299,0.507155

In [33]:
cleaned_conference_baselines.to_csv('cleaned_conference_baselines.csv')